version: '3.8'
services:
  app:
    build: 
      context: .
    volumes:
      - .:/chat-front
    ports:
      - 3000:3000
    image: chat-front
    container_name: chat-front_container
    command: npm start